theme: minima 
title: Anthony's Adventures Around ISD!
author: Anthony Toms Jr
email: anthonytoms12@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This is Anthony. I just started a summer job at KUB. One of the things I'm learning here is well... writing and creating this blog! The blog will detail what things I learn and my experience as well. Hope you enjoy, whoever is reading this right now...

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  atoms2003 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
